[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_yml = "0.0.7"
reqwest = "0.12"
anyhow = "1.0"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
